// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hotellisting.api.Data;

#nullable disable

namespace hotellisting.api.Migrations
{
    [DbContext(typeof(HotelListingDbContext))]
    [Migration("20230222204007_SeededCountriesandHotels")]
    partial class SeededCountriesandHotels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("hotellisting.api.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryCode = "US",
                            Name = "United States"
                        },
                        new
                        {
                            Id = 2,
                            CountryCode = "BH",
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 3,
                            CountryCode = "IT",
                            Name = "Italy"
                        });
                });

            modelBuilder.Entity("hotellisting.api.Data.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "test1234",
                            CountryId = 1,
                            Name = "Marriot",
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 2,
                            Address = "One Ocean",
                            CountryId = 2,
                            Name = "Holiday Inn",
                            Rating = 3.0
                        },
                        new
                        {
                            Id = 3,
                            Address = "The Villa",
                            CountryId = 3,
                            Name = "VillaSuites",
                            Rating = 4.0
                        });
                });

            modelBuilder.Entity("hotellisting.api.Data.Hotel", b =>
                {
                    b.HasOne("hotellisting.api.Data.Country", "Country")
                        .WithMany("Hotels")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("hotellisting.api.Data.Country", b =>
                {
                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
